vich_uploader:
    db_driver: orm

    mappings:
        students:
            uri_prefix: /images/students
            upload_destination: '%kernel.project_dir%/public/images/students'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
